// English
admin_panel: 'Admin Panel 👮',
platform_overview: 'Platform Overview',
dashboard: 'Dashboard',
user_management: 'User Management',
complaints: 'Complaints',
reviews_moderation: 'Reviews',
reports: 'Reports',
platform_cashflow: 'Cashflow',
platform_stats: '📊 Platform Stats',
seekers: 'Seekers',
providers: 'Providers',
pending: 'Pending',
requests: 'Requests',
completed: 'Completed',
revenue_etb: 'Revenue ETB',
pending_providers: '⏳ Pending Providers',
registered: 'Registered',
view_id: 'View ID',
verify: 'Verify',
reject: 'Reject',
all_users: 'All Users',
status: 'Status',
suspend: 'Suspend',
activate: 'Activate',
complaints_count: 'Complaints',
cancelled_requests: 'Cancelled requests',
open_complaints: 'Open Complaints',
complaint: 'Complaint',
reporter: 'Reporter',
against: 'Against',
reason: 'Reason',
date: 'Date',
resolve: 'Resolve',
all_reviews: 'All Reviews',
review_by: 'Review by',
delete: 'Delete',
generate_report: 'Generate Report',
select_report_type: 'Select report type',
users: 'Users',
transactions: 'Transactions',
generate: 'Generate',
recent_transactions: 'Recent Transactions',
close: 'Close',
loading: 'Loading...',
confirm_user_status: 'Are you sure you want to {action} {name}?',
user_status_updated: 'User status updated to {status}',
provider_activated: 'Provider activated successfully.',
activate_provider_confirm: 'Activate "{name}" as a verified provider?',
resolve_complaint: 'Resolve Complaint',
resolve_confirm: 'Mark this complaint as resolved?',
complaint_resolved: 'Complaint resolved.',
delete_review: 'Delete Review',
delete_review_confirm: 'Are you sure you want to delete this review? This cannot be undone.',
review_deleted: 'Review deleted.',
report: 'Report',
success: 'Success',

// Amharic
admin_panel: 'የአስተዳዳሪ ፓነል 👮',
platform_overview: 'የመድረክ አጠቃላይ እይታ',
dashboard: 'ዳሽቦርድ',
user_management: 'የተጠቃሚ አስተዳደር',
complaints: 'ቅሬታዎች',
reviews_moderation: 'ግምገማዎች',
reports: 'ሪፖርቶች',
platform_cashflow: 'የገንዘብ ፍሰት',
platform_stats: '📊 የመድረክ ስታቲስቲክስ',
seekers: 'ፈላጊዎች',
providers: 'አቅራቢዎች',
pending: 'በመጠባበቅ ላይ',
requests: 'ጥያቄዎች',
completed: 'ተጠናቀቀ',
revenue_etb: 'ገቢ ብር',
pending_providers: '⏳ በመጠባበቅ ላይ ያሉ አቅራቢዎች',
registered: 'ተመዝግቧል',
view_id: 'መታወቂያ ይመልከቱ',
verify: 'አረጋግጥ',
reject: 'ውድቅ',
all_users: 'ሁሉም ተጠቃሚዎች',
status: 'ሁኔታ',
suspend: 'እገዳ',
activate: 'አንቃ',
complaints_count: 'ቅሬታዎች',
cancelled_requests: 'የተሰረዙ ጥያቄዎች',
open_complaints: 'ክፍት ቅሬታዎች',
complaint: 'ቅሬታ',
reporter: 'አቅራቢ',
against: 'በላይ',
reason: 'ምክንያት',
date: 'ቀን',
resolve: 'ፍታ',
all_reviews: 'ሁሉም ግምገማዎች',
review_by: 'ግምገማ በ',
delete: 'ሰርዝ',
generate_report: 'ሪፖርት ፍጠር',
select_report_type: 'የሪፖርት አይነት ይምረጡ',
users: 'ተጠቃሚዎች',
transactions: 'ግብይቶች',
generate: 'ፍጠር',
recent_transactions: 'የቅርብ ጊዜ ግብይቶች',
close: 'ዝጋ',
loading: 'በመጫን ላይ...',
confirm_user_status: '{action} {name} ብለው እርግጠኛ ነዎት?',
user_status_updated: 'የተጠቃሚ ሁኔታ ወደ {status} ተቀይሯል',
provider_activated: 'አቅራቢ በሚገባ ነቃ።',
activate_provider_confirm: '"{name}" እንደ የተረጋገጠ አቅራቢ ማግበር ይፈልጋሉ?',
resolve_complaint: 'ቅሬታ ፍታ',
resolve_confirm: 'ይህ ቅሬታ እንደተፈታ ምልክት ማድረግ ይፈልጋሉ?',
complaint_resolved: 'ቅሬታ ተፈትቷል።',
delete_review: 'ግምገማ ሰርዝ',
delete_review_confirm: 'ይህን ግምገማ መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት? ይህ ሊቀለበስ አይችልም።',
review_deleted: 'ግምገማ ተሰርዟል።',
report: 'ሪፖርት',
success: 'ተሳክቷል',